# -*- coding: utf-8 -*-
"""kaggle_predicao_destino_naive_PedroCamara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbGbMaOMkYCoNbVyoJKPvMAKa-gf_5XO

Neste notebook vamos construir um pipeline simples para entender o dataset da competição e treinar um primeiro modelo preditivo. O objetivo aqui é te equipar com as ferramentas para testar suas próprias ideias.
"""

from google.colab import drive
drive.mount('/content/drive')

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import folium
from sklearn.ensemble import RandomForestRegressor

train = pd.read_csv("/content/drive/MyDrive/Classroom/[CTE-IA] Tópicos Especiais em Aprendizado de Máquina Profs. José Macêdo (DC UFC) e Régis Pires (Quixadá UFC)/Desafio Kaggle/train.csv")
test = pd.read_csv("/content/drive/MyDrive/Classroom/[CTE-IA] Tópicos Especiais em Aprendizado de Máquina Profs. José Macêdo (DC UFC) e Régis Pires (Quixadá UFC)/Desafio Kaggle/test.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)

train

test

"""
Cada linha contém:

* `trajectory_id`: id único da trajetória
* `user_id`: pessoa que gerou o caminho
* `n_points`: número total de pontos da trajetória original
* `prefix_ratio`: porcentagem usada como prefixo
* `prefix_n_points`: quantidade de pontos no prefixo
* `path_lat` e `path_lon`: **listas (sequências)** de pontos de latitude e longitude
* `dest_lat` e `dest_lon`: destino real (somente no train)

**O prefixo é a parte inicial do caminho**, e é isso que damos ao modelo para prever o destino final.

Por que prefixo?

Porque na vida real, normalmente queremos prever algo ANTES do trajeto terminar.
Exemplo: “Para onde essa pessoa vai?”, usando apenas o começo do trajeto.

## EDA — Análise Exploratória
Vamos começar entendendo o conjunto de dados. Vamos verificar pontos mais básicos.

#### Quantas trajetórias cada usuário tem?

1.   Item da lista
2.   Item da lista



Isso ajuda a perceber se alguns usuários estão super-representados."""

train["user_id"].value_counts().head(10)

"""#### Quantos pontos tem cada prefixo?


Trajetórias com poucos pontos são difíceis de usar, enquanto trajetórias longas carregam mais informação.
"""

plt.figure(figsize=(8,4))
plt.hist(train["prefix_n_points"], bins=50)
plt.title("Distribuição dos tamanhos do prefixo")
plt.xlabel("Quantidade de pontos")
plt.ylabel("Frequência")
plt.show()

"""#### Quais são os destinos mais comuns?

Não significa que muitos destinos são iguais, só que algumas pessoas têm rotinas estáveis.
"""

train["dest_pair"] = (
    train["dest_lat"].round(4).astype(str) + "," +
    train["dest_lon"].round(4).astype(str)
)

train["dest_pair"].value_counts().head(10)

"""Selecionando uma trajetória por usuário

Escolhemos intencionalmente a mais longa, pois normalmente é a que melhor mostra os padrões daquele usuário.
"""

best_traj = (
    train.sort_values("prefix_n_points", ascending=False)
         .groupby("user_id")
         .head(1)
)
best_traj

"""## Visualizando trajetórias no mapa

Para visualizar rotas, vamos usar o Folium, que cria mapas interativos. Vamos mostrar a maior trajetória de cada usuário (como exemplo visual).
"""

# mapa centralizado em Pequim (região do dataset)
m = folium.Map(location=[39.9, 116.3], zoom_start=11)

# folium.TileLayer(tiles="OpenStreetMap", opacity=0.3, name="OSM Esmaecido").add_to(m)
folium.TileLayer(tiles="CartoDB Dark_Matter", name="Mapa Esmaecido").add_to(m)  # ou CartoDB Positron

N = len(best_traj)

# Tab20 tem 20 cores discretas internas
cmap = plt.colormaps["tab20"]

# linspace(0, 1, N) gera N valores igualmente espaçados entre 0 e 1
# Para N=20, retorna exatamente os 20 slots do Tab20
colors_list = [mcolors.to_hex(cmap(i)) for i in np.linspace(0, 1, N)]

for (color, (_, row)) in zip(colors_list, best_traj.iterrows()):
    lat_list = json.loads(row["path_lat"])
    lon_list = json.loads(row["path_lon"])
    coords = list(zip(lat_list, lon_list))

    folium.PolyLine(coords, color=color, weight=2).add_to(m)

m

"""## Construindo o modelo baseline

prever o destino final da trajetória usando apenas o prefixo.

Como ponto de partida, vamos criar um modelo simples usando features básicas da rota. A abordagem desse exemplo será extraindo features básicas das rotas.

Vamos extrair:

* posição inicial
* posição final do prefixo
"""

import math

def haversine_np(lat1, lon1, lat2, lon2):
    R = 6371000
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))


def bearing(lat1, lon1, lat2, lon2):
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlon = lon2 - lon1
    x = np.sin(dlon) * np.cos(lat2)
    y = np.cos(lat1)*np.sin(lat2) - np.sin(lat1)*np.cos(lat2)*np.cos(dlon)
    return np.arctan2(x, y)

def extract_features(df):
    feats = []

    for _, row in df.iterrows():
        lats = json.loads(row["path_lat"])
        lons = json.loads(row["path_lon"])

        start_lat, start_lon = lats[0], lons[0]
        end_lat, end_lon     = lats[-1], lons[-1]

        dist = haversine_np(start_lat, start_lon, end_lat, end_lon)
        dirc = bearing(start_lat, start_lon, end_lat, end_lon)


        feats.append({
            "start_lat": start_lat,
            "start_lon": start_lon,
            "end_lat": end_lat,
            "end_lon": end_lon,
            "delta_lat": end_lat - start_lat,
            "delta_lon": end_lon - start_lon,
            "distance": dist,
            "speed_approx": dist / len(lats),
            "bearing_sin": np.sin(dirc),
            "bearing_cos": np.cos(dirc),
            "n_points": len(lats),
            # "prefix_ratio": row["prefix_n_points"],
            "prefix_ratio": row["prefix_n_points"] / row["n_points"]
        })

    return pd.DataFrame(feats)

"""Primeiro, vamos criar um conjunto de treino e validação.

"""

train

from sklearn.model_selection import train_test_split

# divide o treino em treino interno + validação (20%)
train_split, val_split = train_test_split(train, test_size=0.2, random_state=42)

# extrai features
X_train = extract_features(train_split)
X_val   = extract_features(val_split)

# variáveis alvo
y_train_lat = train_split["dest_lat"]
y_train_lon = train_split["dest_lon"]

y_val_lat = val_split["dest_lat"]
y_val_lon = val_split["dest_lon"]

X_train

X_val

y_train_lat

y_train_lon

# model_lat = RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)
# model_lon = RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1)

model_lat = RandomForestRegressor(
    n_estimators=300, # Reduz variância
     random_state=42,
    n_jobs=-1
)

model_lon = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

model_lat.fit(X_train, y_train_lat)
model_lon.fit(X_train, y_train_lon)

"""Agora com o modelo treinado vamos fazer a predição no conjunto de validação."""

pred_lat_val = model_lat.predict(X_val)
pred_lon_val = model_lon.predict(X_val)

pred_lat_val, pred_lon_val

"""Vamos avaliar a qualidade das predições (erro) desse modelo no conjunto de validação. Primeiro vamos implementar a métrica haversine ponto a ponto.  

"""

def haversine(lat1, lon1, lat2, lon2):
    """
    Retorna a distância Haversine em metros entre dois pontos (lat, lon).
    """
    R = 6371000  # raio da Terra em metros

    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    return R * c

errors = haversine(
    y_val_lat.values,
    y_val_lon.values,
    pred_lat_val,
    pred_lon_val
)

mean_error = errors.mean()

print(f"Distância Haversine média em quilômetros no conjunto de validação: {mean_error/1000:.2f} km")

# Construir um DataFrame com verdade e predição lado a lado
val_vis = val_split.copy().reset_index(drop=True)
val_vis["pred_lat"] = pred_lat_val
val_vis["pred_lon"] = pred_lon_val

# Para não deixar o mapa pesado, pegamos uma amostra de trajetórias
N_SAMPLE = 50  # você pode ajustar
if len(val_vis) > N_SAMPLE:
    val_sample = val_vis.sample(N_SAMPLE, random_state=42)
else:
    val_sample = val_vis

m = folium.Map(location=[39.9, 116.3], zoom_start=11)
folium.TileLayer(tiles="CartoDB Positron", name="Mapa Esmaecido").add_to(m)  # ou CartoDB Dark_Matter

# Adicionar pontos e linhas no mapa
for _, row in val_sample.iterrows():
    real_lat = row["dest_lat"]
    real_lon = row["dest_lon"]
    pred_lat = row["pred_lat"]
    pred_lon = row["pred_lon"]

    # Marcador do destino real (verde)
    folium.CircleMarker(
        location=[real_lat, real_lon],
        radius=3,
        color="green",
        fill=True,
        fill_color="green",
        fill_opacity=0.7,
        popup=f"REAL: ({real_lat:.5f}, {real_lon:.5f})"
    ).add_to(m)

    # Marcador do destino previsto (vermelho)
    folium.CircleMarker(
        location=[pred_lat, pred_lon],
        radius=3,
        color="red",
        fill=True,
        fill_color="red",
        fill_opacity=0.7,
        popup=f"PREDITO: ({pred_lat:.5f}, {pred_lon:.5f})"
    ).add_to(m)

    # Linha ligando real ↔ previsto
    folium.PolyLine(
        locations=[[real_lat, real_lon], [pred_lat, pred_lon]],
        color="blue",
        weight=1,
        opacity=0.5
    ).add_to(m)

m

"""## Usando os modelos trainados para obter as predições de latitude e longitude"""

X_test   = extract_features(test)
pred_lat = model_lat.predict(X_test)
pred_lon = model_lon.predict(X_test)

X_test

submission = pd.DataFrame({
    "trajectory_id": test["trajectory_id"],
    "latitude_pred": pred_lat,
    "longitude_pred": pred_lon
})

submission.to_csv("submission1.csv", index=False)
submission.head()

"""## Obtendo a latitude e longitude médias para o conjunto de dados de treino"""

media_lat_train = train['dest_lat'].mean()
media_lat_train

media_lon_train = train['dest_lon'].mean()
media_lon_train

"""## Gerando uma submissão (ruim) baseada na média"""

submission_media = pd.DataFrame({
    "trajectory_id": test["trajectory_id"],
    "latitude_pred": media_lat_train,
    "longitude_pred": media_lon_train
})

submission_media.to_csv("submission-media.csv", index=False)
submission_media.head()

from google.colab import files
files.download('submission1.csv')